language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

sudo: required

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build jacocoTestReport check