language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

sudo: required

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build jacocoTestReport check
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  